version: "3"

services:
  app:
    image: golang:1.9-alpine
    volumes: 
      - .:/go/src/github.com/form3
    working_dir: /go/src/github.com/form3
    command: go run main.go
    links:
      - mongo
    environment:
    - MONGO_URI=mongo:27017
    container_name: "form3_service"
 
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"



  
 

